run:
  deadline: 5m
issues:
  exclude-use-default: false
linters:
  enable:
  - deadcode
  - depguard
  - gofmt
  - goimports
  - golint
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - typecheck
  - unused
  - varcheck
  # TODO: enable more linters!
  # - dupl
  # - gochecknoglobals
  # - gochecknoinits
  # - goconst
  # - gocyclo
  # - gosec
  # - interfacer
  # - lll
  # - maligned
  # - prealloc
  # - scopelint
  # - stylecheck
  # - unconvert
  # - unparam
  disable:
  - errcheck
  - staticcheck
  - structcheck
